server:
  port: 8080

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: booking-route
#          uri: ${domains.booking-service}
#          predicates:
#            - Path=/bookings/**
#        - id: order-route
#          uri: ${domains.order-service}
#          predicates:
#            - Path=/orders/**

domains:
  booking-service: http://localhost:8081
  order-service: http://localhost:8082
